export const INIT_AUTH = 'INIT_AUTH';
export const AUTH_START = 'AUTH_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';

export const RECOVER_PASSWORD_START = 'RECOVER_PASSWORD_START';
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';
export const RECOVER_PASSWORD_FAIL = 'RECOVER_PASSWORD_FAIL';
export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';




export const GET_USER_COMPANY_SUCCESS ='GET_USER_COMPANY_SUCCESS';
export const GET_USER_COMPANY_FAIL ='GET_USER_COMPANY_FAIL';


export const CREATE_ROUND_SUCCESS = 'CREATE_ROUND_SUCCESS';
export const CREATE_ROUND_FAIL = 'CREATE_ROUND_FAIL';
